global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8087']

  - job_name: 'patient-identity-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['patient-identity-service:8081']

  - job_name: 'emr-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['emr-service:8082']

  - job_name: 'appointment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['appointment-service:8083']

  - job_name: 'telemedicine-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['telemedicine-service:8084']

  - job_name: 'pharmacy-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pharmacy-service:8085']

  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-service:8086']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8088']

  - job_name: 'ussd-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ussd-service:8089']
